# Generated by Django 5.2.1 on 2025-06-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_phone', models.CharField(blank=True, max_length=30)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('gst_exempt', models.CharField(blank=True, max_length=50)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=30)),
                ('bsb', models.CharField(blank=True, max_length=20)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
